#!/bin/bash
# ─────────────────────────────────────────────────────────
# deploy-frontend.sh
# Uploads the static dashboard files to the S3 bucket created
# by the SAM template. Run after `sam deploy`.
#
# Usage:
#   ./scripts/deploy-frontend.sh
#
# Prerequisites:
#   - AWS CLI configured with credentials
#   - SAM stack already deployed (to create the S3 bucket)
#   - API_URL from the stack outputs (injected into config.js)
# ─────────────────────────────────────────────────────────

set -euo pipefail

STACK_NAME="${STACK_NAME:-nge-sentinel-monitor}"
REGION="${AWS_REGION:-us-east-1}"

echo "Fetching stack outputs..."

# Get the S3 bucket name and API URL from CloudFormation outputs
BUCKET=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='DashboardBucketName'].OutputValue" \
  --output text)

API_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='ApiUrl'].OutputValue" \
  --output text)

if [ -z "$BUCKET" ] || [ "$BUCKET" = "None" ]; then
  echo "ERROR: Could not find DashboardBucketName in stack outputs."
  echo "       Make sure the stack '$STACK_NAME' is deployed."
  exit 1
fi

echo "Bucket:  $BUCKET"
echo "API URL: $API_URL"

# Create a config file that injects the API URL into the frontend
cat > frontend/js/config.js << EOF
// Auto-generated by deploy-frontend.sh — do not edit manually.
// This file is created at deploy time with the actual API Gateway URL.
window.SENTINEL_API_URL = "${API_URL}";
EOF

echo "Generated frontend/js/config.js with API URL"

# Upload all frontend files to S3
echo "Uploading frontend to s3://$BUCKET/..."
aws s3 sync frontend/ "s3://$BUCKET/" \
  --region "$REGION" \
  --delete \
  --cache-control "max-age=300"

# Get the website URL
WEBSITE_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK_NAME" \
  --region "$REGION" \
  --query "Stacks[0].Outputs[?OutputKey=='DashboardUrl'].OutputValue" \
  --output text)

echo ""
echo "Dashboard deployed successfully!"
echo "  URL: $WEBSITE_URL"
echo "  API: $API_URL"
