#!/usr/bin/env bash
# deploy-demo.sh — Deploy all NGE contracts and generate frontend .env
#
# Usage:
#   # Deploy to local Hardhat node (no Sepolia ETH needed):
#   ./scripts/deploy-demo.sh local
#
#   # Deploy to Sepolia (requires DEPLOYER_PRIVATE_KEY + ETH_RPC_URL):
#   ./scripts/deploy-demo.sh sepolia
#
# Prerequisites:
#   npm ci in each project directory (script does this automatically)
#
# For local mode:
#   1. Start a Hardhat node first:  cd projects/nge-token && npx hardhat node
#   2. Add localhost:8545 network to MetaMask (Chain ID: 31337)
#   3. Import the first Hardhat account into MetaMask (key printed by hardhat node)
#
# For Sepolia mode:
#   export DEPLOYER_PRIVATE_KEY=0x_your_key
#   export ETH_RPC_URL=https://sepolia.infura.io/v3/YOUR_KEY

set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
NETWORK="${1:-local}"
FRONTEND_ENV="$ROOT_DIR/projects/nge-frontend/.env"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[FAIL]${NC}  $*"; exit 1; }

# ─── Validate ──────────────────────────────────────────────
if [[ "$NETWORK" == "sepolia" ]]; then
  [[ -z "${DEPLOYER_PRIVATE_KEY:-}" ]] && fail "DEPLOYER_PRIVATE_KEY not set. Export it before running."
  [[ -z "${ETH_RPC_URL:-}" ]] && fail "ETH_RPC_URL not set. Export it before running."
  info "Deploying to Sepolia"
elif [[ "$NETWORK" == "local" ]]; then
  # For local Hardhat node, use default account
  export ETH_RPC_URL="http://127.0.0.1:8545"
  # Hardhat's default account #0 private key
  export DEPLOYER_PRIVATE_KEY="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
  info "Deploying to local Hardhat node at $ETH_RPC_URL"
  warn "Make sure you started a node:  cd projects/nge-token && npx hardhat node"
else
  fail "Unknown network: $NETWORK (use 'local' or 'sepolia')"
fi

# ─── Helper: extract address from deploy output ───────────
extract_address() {
  grep -oP '0x[0-9a-fA-F]{40}' | head -1
}

# ─── Install + Compile + Deploy for a project ────────────
deploy_project() {
  local project="$1"
  local dir="$ROOT_DIR/projects/$project"

  info "─── Deploying $project ───"

  cd "$dir"

  # Install if needed
  if [[ ! -d "node_modules" ]]; then
    info "Installing dependencies for $project..."
    npm ci --silent
  fi

  # Compile
  info "Compiling $project contracts..."
  npx hardhat compile --quiet

  # Deploy
  info "Deploying $project to $NETWORK..."
  local output
  if [[ "$NETWORK" == "local" ]]; then
    output=$(npx hardhat run scripts/deploy.js --network localhost 2>&1)
  else
    output=$(npx hardhat run scripts/deploy.js --network sepolia 2>&1)
  fi

  echo "$output"
  local address
  address=$(echo "$output" | extract_address)

  if [[ -z "$address" ]]; then
    fail "Failed to extract contract address from $project deploy output"
  fi

  ok "$project deployed to: $address"
  echo "$address"
}

# ─── Deploy all three contracts ───────────────────────────
echo ""
info "=========================================="
info "  NGE Demo Deployment — $NETWORK"
info "=========================================="
echo ""

SENTINEL_ADDRESS=$(deploy_project "nge-sentinel")
# Get just the last line (the address)
SENTINEL_ADDRESS=$(echo "$SENTINEL_ADDRESS" | tail -1)
echo ""

IOT_ADDRESS=$(deploy_project "nge-iot")
IOT_ADDRESS=$(echo "$IOT_ADDRESS" | tail -1)
echo ""

TOKEN_ADDRESS=$(deploy_project "nge-token")
TOKEN_ADDRESS=$(echo "$TOKEN_ADDRESS" | tail -1)
echo ""

# ─── Generate frontend .env ──────────────────────────────
info "Generating frontend .env..."

if [[ "$NETWORK" == "local" ]]; then
  CHAIN_ID="31337"
  CHAIN_NAME="Localhost"
  EXPLORER_URL=""
else
  CHAIN_ID="11155111"
  CHAIN_NAME="Sepolia"
  EXPLORER_URL="https://sepolia.etherscan.io"
fi

cat > "$FRONTEND_ENV" <<EOF
# Auto-generated by deploy-demo.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# Network: $NETWORK

# Contract addresses
REACT_APP_TOKEN_ADDRESS=$TOKEN_ADDRESS
REACT_APP_IOT_ADDRESS=$IOT_ADDRESS
REACT_APP_SENTINEL_ADDRESS=$SENTINEL_ADDRESS

# Network
REACT_APP_CHAIN_ID=$CHAIN_ID
REACT_APP_CHAIN_NAME=$CHAIN_NAME
REACT_APP_EXPLORER_URL=$EXPLORER_URL

# API endpoints (update after deploying AWS infrastructure)
REACT_APP_TOKEN_API=
REACT_APP_SENTINEL_API=

# Cognito auth (update after deploying nge-auth stack)
REACT_APP_COGNITO_USER_POOL_ID=
REACT_APP_COGNITO_CLIENT_ID=
REACT_APP_COGNITO_REGION=us-east-1
EOF

ok "Frontend .env written to: $FRONTEND_ENV"

# ─── Summary ─────────────────────────────────────────────
echo ""
info "=========================================="
info "  Deployment Complete!"
info "=========================================="
echo ""
echo -e "  ${GREEN}Token:${NC}    $TOKEN_ADDRESS"
echo -e "  ${GREEN}IoT:${NC}      $IOT_ADDRESS"
echo -e "  ${GREEN}Sentinel:${NC} $SENTINEL_ADDRESS"
echo ""
echo -e "  ${CYAN}Frontend .env:${NC} $FRONTEND_ENV"
echo ""

if [[ "$NETWORK" == "sepolia" ]]; then
  echo -e "  ${CYAN}View on Etherscan:${NC}"
  echo "    Token:    https://sepolia.etherscan.io/address/$TOKEN_ADDRESS"
  echo "    IoT:      https://sepolia.etherscan.io/address/$IOT_ADDRESS"
  echo "    Sentinel: https://sepolia.etherscan.io/address/$SENTINEL_ADDRESS"
  echo ""
fi

echo "  Next steps:"
echo "    1. cd projects/nge-frontend"
echo "    2. npm start"
echo "    3. Connect MetaMask to $CHAIN_NAME"
echo ""
EOF
